#!/usr/bin/env bash

set -e

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew tap caskroom/cask
brew tap homebrew/services

brew install \
    git \
    wget \
    gcc \
    curl \
    python3 \
    # time tracker
    watson \
    # file change monitor
    fswatch \
    # media player
    mpv \
    # paper backup for GPG
    paperkey

brew cask install \
    iterm2 \
    # managing windows size and position
    shiftit \
    docker \
    emacs \
    visual-studio-code \
    skype \
    telegram-desktop \
    firefox \
    chromium \
    torbrowser \
    java \
    julia \
    # utility for keyboard customization
    karabiner-elements

brew install bash-completion
